// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createUserSession = `-- name: CreateUserSession :one

INSERT INTO user_sessions (
    user_id,
    refresh_token_hash,
    user_agent,
    ip,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, refresh_token_hash, user_agent, ip, expires_at, created_at
`

type CreateUserSessionParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	Ip               pqtype.Inet    `json:"ip"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

// User session management queries
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, createUserSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.Ip,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions
WHERE id = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserSession, id)
	return err
}

const deleteUserSessionByHash = `-- name: DeleteUserSessionByHash :exec
DELETE FROM user_sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteUserSessionByHash(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessionByHash, refreshTokenHash)
	return err
}

const deleteUserSessionsByUserID = `-- name: DeleteUserSessionsByUserID :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessionsByUserID, userID)
	return err
}

const getUserSessionByHash = `-- name: GetUserSessionByHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip, expires_at, created_at
FROM user_sessions
WHERE refresh_token_hash = $1
LIMIT 1
`

func (q *Queries) GetUserSessionByHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionByHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.Ip,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
