// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Announcement struct {
	ID        uuid.UUID     `json:"id"`
	Title     string        `json:"title"`
	Body      string        `json:"body"`
	Audience  string        `json:"audience"`
	PublishAt sql.NullTime  `json:"publish_at"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type ApplicationEvent struct {
	ID            uuid.UUID      `json:"id"`
	ApplicationID uuid.UUID      `json:"application_id"`
	StatusFrom    sql.NullString `json:"status_from"`
	StatusTo      sql.NullString `json:"status_to"`
	StaffUserID   uuid.NullUUID  `json:"staff_user_id"`
	Comment       sql.NullString `json:"comment"`
	CreatedAt     time.Time      `json:"created_at"`
}

type IngestionJob struct {
	ID           uuid.UUID             `json:"id"`
	Source       string                `json:"source"`
	Payload      pqtype.NullRawMessage `json:"payload"`
	Status       string                `json:"status"`
	ProcessedAt  sql.NullTime          `json:"processed_at"`
	ErrorMessage sql.NullString        `json:"error_message"`
	CreatedAt    time.Time             `json:"created_at"`
}

type Job struct {
	ID           uuid.UUID      `json:"id"`
	Title        string         `json:"title"`
	Slug         string         `json:"slug"`
	Summary      sql.NullString `json:"summary"`
	Description  string         `json:"description"`
	LocationID   sql.NullInt64  `json:"location_id"`
	ContractType sql.NullString `json:"contract_type"`
	WorkPattern  sql.NullString `json:"work_pattern"`
	SalaryMin    sql.NullInt32  `json:"salary_min"`
	SalaryMax    sql.NullInt32  `json:"salary_max"`
	Currency     sql.NullString `json:"currency"`
	Status       string         `json:"status"`
	Source       sql.NullString `json:"source"`
	SourceRef    sql.NullString `json:"source_ref"`
	PostedAt     sql.NullTime   `json:"posted_at"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type JobApplication struct {
	ID          uuid.UUID             `json:"id"`
	JobID       uuid.UUID             `json:"job_id"`
	UserID      uuid.UUID             `json:"user_id"`
	Status      string                `json:"status"`
	CoverLetter sql.NullString        `json:"cover_letter"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	SubmittedAt time.Time             `json:"submitted_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type JobJobTag struct {
	JobID uuid.UUID `json:"job_id"`
	TagID uuid.UUID `json:"tag_id"`
}

type JobLocation struct {
	ID        int64          `json:"id"`
	Country   string         `json:"country"`
	Region    sql.NullString `json:"region"`
	City      sql.NullString `json:"city"`
	Latitude  sql.NullString `json:"latitude"`
	Longitude sql.NullString `json:"longitude"`
	CreatedAt time.Time      `json:"created_at"`
}

type JobTag struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	CreatedAt time.Time `json:"created_at"`
}

type Resource struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Summary     sql.NullString `json:"summary"`
	Body        string         `json:"body"`
	Category    sql.NullString `json:"category"`
	HeroImage   sql.NullString `json:"hero_image"`
	PublishedAt sql.NullTime   `json:"published_at"`
	Source      sql.NullString `json:"source"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	Status       string       `json:"status"`
	LastLoginAt  sql.NullTime `json:"last_login_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type UserProfile struct {
	UserID          uuid.UUID             `json:"user_id"`
	FirstName       sql.NullString        `json:"first_name"`
	LastName        sql.NullString        `json:"last_name"`
	Phone           sql.NullString        `json:"phone"`
	Location        sql.NullString        `json:"location"`
	Biography       sql.NullString        `json:"biography"`
	Specialties     []string              `json:"specialties"`
	ExperienceYears sql.NullInt32         `json:"experience_years"`
	Availability    pqtype.NullRawMessage `json:"availability"`
	Preferences     pqtype.NullRawMessage `json:"preferences"`
	CreatedAt       time.Time             `json:"created_at"`
	UpdatedAt       time.Time             `json:"updated_at"`
}

type UserSession struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	RefreshTokenHash string         `json:"refresh_token_hash"`
	UserAgent        sql.NullString `json:"user_agent"`
	Ip               pqtype.Inet    `json:"ip"`
	ExpiresAt        time.Time      `json:"expires_at"`
	CreatedAt        time.Time      `json:"created_at"`
}
