# syntax=docker/dockerfile:1
FROM golang:1.25-alpine AS base

WORKDIR /workspace/apps/api

RUN apk add --no-cache build-base git
RUN go install github.com/air-verse/air@v1.52.3

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
